use crate::character::Internal;

#[derive(Debug, Clone)]
pub struct CommonAttributes {
	walk_initial_velocity: f32,
	walk_acceleration: f32,
	walk_max_velocity: f32,
	slow_walk_max: f32,
	mid_walk_point: f32,
	fast_walk_min: f32,
	friction: f32,
	dash_initial_velocity: f32,
	stop_turn_initial_speed_a: f32,
	stop_turn_initial_speed_b: f32,
	max_run_speed: f32,
	run_animation_scaling: f32,
	max_runbrake_frames: f32,
	grounded_max_h_velocity: f32,
	jump_squat_frames: f32,
	jump_initial_h_velocity: f32,
	jump_initial_v_velocity: f32,
	ground_jump_momentum_multiplier: f32,
	short_hop_max_h_velocity: f32,
	short_hop_initial_v_velocity: f32,
	air_jump_h_multiplier: f32,
	air_jump_v_multiplier: f32,
	number_of_jumps: i32,
	gravity: f32,
	terminal_velocity: f32,
	air_mobility_a: f32,
	air_mobility_b: f32,
	max_aerial_h_velocity: f32,
	air_friction: f32,
	fast_fall_terminal_velocity: f32,
	tilt_turn_forced_velocity: f32,
	jab2_window: f32,
	jab3_window: f32,
	turn_duration: f32,
	weight: f32,
	model_scaling: f32,
	shield_size: f32,
	shield_break_initial_velocity: f32,
	rapid_jab_window: i32,
	clank_speed_multiplier: f32,
	hit_by_item_flag: f32,
	unknown0xa4: i32,
	ledgejump_h_velocity: f32,
	ledgejump_v_velocity: f32,
	item_throw_velocity_multiplier: f32,
	item_throw_damage_multiplier: f32,
	run_side_special_momentum: f32,
	egg_size: f32,
	egg_hurtbox: f32,
	egg_hurtbox_x: f32,
	egg_hurtbox_y: f32,
	egg_hurtbox_z: f32,
	unknown0xd0: f32,
	unknown0xd4: f32,
	egg_hurtbox_radius: f32,
	kirby_neutral_special_star_swallow_damage: f32,
	kirby_star_damage: f32,
	normal_landing_lag: f32,
	nair_landing_lag: f32,
	fair_landing_lag: f32,
	bair_landing_lag: f32,
	uair_landing_lag: f32,
	dair_landing_lag: f32,
	victory_screen_model_scaling: f32,
	wall_tech_x: f32,
	wall_jump_h_velocity: f32,
	wall_jump_v_velocity: f32,
	ceiling_tech_x_direction: f32,
	unknown0x110: f32,
	left_bunny_hood_x: f32,
	left_bunny_hood_y: f32,
	left_bunny_hood_z: f32,
	right_bunny_hood_x: f32,
	right_bunny_hood_y: f32,
	right_bunny_hood_z: f32,
	bunny_hood_size: f32,
	flower_x: f32,
	flower_y: f32,
	flower_z: f32,
	flower_size: f32,
	screw_attack_upward_knockback: f32,
	screw_attack_effect_size: f32,
	unknown0x148: f32,
	bubble_ratio: f32,
	freeze_offset1: f32,
	freeze_offset2: f32,
	freeze_escape_height: f32,
	freeze_escape_x_momentum: f32,
	ice_tractionfrozen_size: f32,
	warp_star_hitbox_scaling: f32,
	unknown0x168: f32,
	camera_target_zoom_bone: i32,
	magnified_x_sway: f32,
	magnified_y_sway: f32,
	magnified_z_sway: f32,
	footstool_y_offset: f32,
	weight_dependent_throw_flags: u8,
}

impl CommonAttributes {
	pub fn get(fighter: Internal) -> &'static Self {
		match fighter {
			Internal::Mario => &MARIO_COMMON_ATTRS,
			Internal::Fox => todo!(),
			Internal::CaptainFalcon => todo!(),
			Internal::DonkeyKong => todo!(),
			Internal::Kirby => todo!(),
			Internal::Bowser => todo!(),
			Internal::Link => todo!(),
			Internal::Sheik => todo!(),
			Internal::Ness => todo!(),
			Internal::Peach => todo!(),
			Internal::Popo => todo!(),
			Internal::Nana => todo!(),
			Internal::Pikachu => todo!(),
			Internal::Samus => todo!(),
			Internal::Yoshi => todo!(),
			Internal::Jigglypuff => todo!(),
			Internal::Mewtwo => todo!(),
			Internal::Luigi => todo!(),
			Internal::Marth => todo!(),
			Internal::Zelda => todo!(),
			Internal::YoungLink => todo!(),
			Internal::DrMario => todo!(),
			Internal::Falco => todo!(),
			Internal::Pichu => todo!(),
			Internal::GameAndWatch => todo!(),
			Internal::Ganondorf => todo!(),
			Internal::Roy => todo!(),
			Internal::MasterHand => todo!(),
			Internal::CrazyHand => todo!(),
			Internal::WireFrameMale => todo!(),
			Internal::WireFrameFemale => todo!(),
			Internal::GigaBowser => todo!(),
			Internal::Sandbag => todo!(),
		}
	}
}

pub const MARIO_COMMON_ATTRS: CommonAttributes = CommonAttributes {
	walk_initial_velocity: 0.1,
	walk_acceleration: 0.1,
	walk_max_velocity: 1.1,
	slow_walk_max: 0.18,
	mid_walk_point: 0.44,
	fast_walk_min: 0.7,
	friction: 0.06,
	dash_initial_velocity: 1.5,
	stop_turn_initial_speed_a: 0.06,
	stop_turn_initial_speed_b: 0.02,
	max_run_speed: 1.5,
	run_animation_scaling: 1.45,
	max_runbrake_frames: 30.0,
	grounded_max_h_velocity: 3.0,
	jump_squat_frames: 4.0,
	jump_initial_h_velocity: 1.0,
	jump_initial_v_velocity: 2.3,
	ground_jump_momentum_multiplier: 0.8,
	short_hop_max_h_velocity: 1.5,
	short_hop_initial_v_velocity: 1.4,
	air_jump_h_multiplier: 1.0,
	air_jump_v_multiplier: 0.9,
	number_of_jumps: 2,
	gravity: 0.095,
	terminal_velocity: 1.7,
	air_mobility_a: 0.025,
	air_mobility_b: 0.02,
	max_aerial_h_velocity: 0.86,
	air_friction: 0.016,
	fast_fall_terminal_velocity: 2.3,
	tilt_turn_forced_velocity: 3.0,
	jab2_window: 24.0,
	jab3_window: 24.0,
	turn_duration: 4.0,
	weight: 100.0,
	model_scaling: 1.1,
	shield_size: 10.75,
	shield_break_initial_velocity: 2.5,
	rapid_jab_window: 0,
	clank_speed_multiplier: 16.0,
	hit_by_item_flag: 0.0,
	unknown0xa4: 1,
	ledgejump_h_velocity: 1.0,
	ledgejump_v_velocity: 2.3,
	item_throw_velocity_multiplier: 1.0,
	item_throw_damage_multiplier: 1.0,
	run_side_special_momentum: 0.2,
	egg_size: 2.0,
	egg_hurtbox: 0.0,
	egg_hurtbox_x: 6.0,
	egg_hurtbox_y: 0.0,
	egg_hurtbox_z: 0.0,
	unknown0xd0: 9.0,
	unknown0xd4: 0.0,
	egg_hurtbox_radius: 6.0,
	kirby_neutral_special_star_swallow_damage: 2.2,
	kirby_star_damage: 17.0,
	normal_landing_lag: 4.0,
	nair_landing_lag: 16.0,
	fair_landing_lag: 21.0,
	bair_landing_lag: 15.0,
	uair_landing_lag: 15.0,
	dair_landing_lag: 23.0,
	victory_screen_model_scaling: 20.0,
	wall_tech_x: 0.5,
	wall_jump_h_velocity: 1.3,
	wall_jump_v_velocity: 2.3,
	ceiling_tech_x_direction: 1.0,
	unknown0x110: 0.8,
	left_bunny_hood_x: 0.4,
	left_bunny_hood_y: 1.4,
	left_bunny_hood_z: 0.0,
	right_bunny_hood_x: -0.4,
	right_bunny_hood_y: 1.4,
	right_bunny_hood_z: 0.0,
	bunny_hood_size: 1.0,
	flower_x: 0.0,
	flower_y: 1.5,
	flower_z: 0.0,
	flower_size: 1.0,
	screw_attack_upward_knockback: 3.35,
	screw_attack_effect_size: 1.0,
	unknown0x148: 0.5,
	bubble_ratio: 8.2,
	freeze_offset1: -1.7,
	freeze_offset2: -2.5,
	freeze_escape_height: 2.3,
	freeze_escape_x_momentum: 1.0,
	ice_tractionfrozen_size: 1.0,
	warp_star_hitbox_scaling: 1.0,
	unknown0x168: 1.0,
	camera_target_zoom_bone: 5,
	magnified_x_sway: 0.0,
	magnified_y_sway: 2.0,
	magnified_z_sway: 0.0,
	footstool_y_offset: 0.0,
	weight_dependent_throw_flags: 0,
};
